pluginManagement {
    includeBuild("../release-tools")
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://jitpack.io" }
    }
}
dependencyResolutionManagement {
    versionCatalogs {
        libs {
            from(files("../release-tools/gradle/libs.versions.toml"))
        }
    }
}
include ':app'
rootProject.name = 'Pinball With Pretty Girls'
